#stage1


FROM python:3.9-slim AS builder

WORKDIR /app

COPY . . 

RUN pip install -r requirements.txt --target=/app/deps

#stage2


FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

ENV PYTHONPATH="/app/deps"

EXPOSE 80

CMD ["run.py"]
